//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BehaviourOverrides) DeepCopyInto(out *BehaviourOverrides) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BehaviourOverrides.
func (in *BehaviourOverrides) DeepCopy() *BehaviourOverrides {
	if in == nil {
		return nil
	}
	out := new(BehaviourOverrides)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Entity) DeepCopyInto(out *Entity) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Entity.
func (in *Entity) DeepCopy() *Entity {
	if in == nil {
		return nil
	}
	out := new(Entity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HealthEvent) DeepCopyInto(out *HealthEvent) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HealthEvent.
func (in *HealthEvent) DeepCopy() *HealthEvent {
	if in == nil {
		return nil
	}
	out := new(HealthEvent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HealthEvent) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HealthEventList) DeepCopyInto(out *HealthEventList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HealthEvent, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HealthEventList.
func (in *HealthEventList) DeepCopy() *HealthEventList {
	if in == nil {
		return nil
	}
	out := new(HealthEventList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HealthEventList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HealthEventSpec) DeepCopyInto(out *HealthEventSpec) {
	*out = *in
	if in.IsFatal != nil {
		in, out := &in.IsFatal, &out.IsFatal
		*out = new(bool)
		**out = **in
	}
	if in.IsHealthy != nil {
		in, out := &in.IsHealthy, &out.IsHealthy
		*out = new(bool)
		**out = **in
	}
	if in.ErrorCode != nil {
		in, out := &in.ErrorCode, &out.ErrorCode
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.EntitiesImpacted != nil {
		in, out := &in.EntitiesImpacted, &out.EntitiesImpacted
		*out = make([]*Entity, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(Entity)
				**out = **in
			}
		}
	}
	if in.Metadata != nil {
		in, out := &in.Metadata, &out.Metadata
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.GeneratedTimestamp != nil {
		in, out := &in.GeneratedTimestamp, &out.GeneratedTimestamp
		*out = (*in).DeepCopy()
	}
	if in.QuarantineOverrides != nil {
		in, out := &in.QuarantineOverrides, &out.QuarantineOverrides
		*out = new(BehaviourOverrides)
		**out = **in
	}
	if in.DrainOverrides != nil {
		in, out := &in.DrainOverrides, &out.DrainOverrides
		*out = new(BehaviourOverrides)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HealthEventSpec.
func (in *HealthEventSpec) DeepCopy() *HealthEventSpec {
	if in == nil {
		return nil
	}
	out := new(HealthEventSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HealthEventStatus) DeepCopyInto(out *HealthEventStatus) {
	*out = *in
	if in.NodeQuarantined != nil {
		in, out := &in.NodeQuarantined, &out.NodeQuarantined
		*out = new(Status)
		**out = **in
	}
	out.UserPodsEvictionStatus = in.UserPodsEvictionStatus
	if in.FaultRemediated != nil {
		in, out := &in.FaultRemediated, &out.FaultRemediated
		*out = new(bool)
		**out = **in
	}
	if in.LastRemediationTimestamp != nil {
		in, out := &in.LastRemediationTimestamp, &out.LastRemediationTimestamp
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HealthEventStatus.
func (in *HealthEventStatus) DeepCopy() *HealthEventStatus {
	if in == nil {
		return nil
	}
	out := new(HealthEventStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OperationStatus) DeepCopyInto(out *OperationStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OperationStatus.
func (in *OperationStatus) DeepCopy() *OperationStatus {
	if in == nil {
		return nil
	}
	out := new(OperationStatus)
	in.DeepCopyInto(out)
	return out
}
